name       : python-bcrypt
version    : 3.1.0
release    : 1
source     :
    - https://pypi.python.org/packages/9b/32/1ece045aa19069ca687d5ccd1241e03a70cae157ae908b6aa5b97789e6da/bcrypt-3.1.0.tar.gz : e54820d8b9eff357d1003f5b8d4b949a632b76b89610d8a933783fd476033ebe
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-cparser
    - python-setuptools
rundeps    :
    - python-cffi
    - python-cparser
build      : |    
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
