name       : python-bcrypt
version    : 4.0.1
release    : 11
source     :
    - https://github.com/pyca/bcrypt/archive/refs/tags/4.0.1.tar.gz : eea4785805e20197214ab5f81a508668f88df691bc8644f5fc0b3e6621df2633
homepage   : https://github.com/pyca/bcrypt
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
networking : yes
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-pytest
    - python-setuptools-rust
rundeps    :
    - python-cffi
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
