name       : python-bcrypt
version    : 3.1.4
release    : 5
source     :
    - https://github.com/pyca/bcrypt/archive/3.1.4.tar.gz : ca122a2cdcdffb0fd04f9dfe3493766f298bef02dea2f190f35ea6fdee222b96
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-pytest
rundeps    :
    - python-cffi
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
