name       : python-bcrypt
version    : 3.2.0
release    : 10
source     :
    - https://github.com/pyca/bcrypt/archive/refs/tags/3.2.0.tar.gz : da18f9af11ec41c57daf3758f9d21bd90292c0cdb2a7ea4e6b803f39e753c350
homepage   : https://github.com/pyca/bcrypt
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-pytest
rundeps    :
    - python-cffi
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
