name       : python-bcrypt
version    : 3.1.3
release    : 2
source     :
    - https://github.com/pyca/bcrypt/archive/3.1.3.tar.gz : 3ec44481ac655754aa1a1c4ef6211f77343e0c48d2b3ce0446e81ad8336e104b
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
builddeps  :
    - pkgconfig(python-3.5)
    - python-cffi
    - python-pytest
    - python-setuptools
rundeps    :
    - python-cffi
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    export LC_ALL=en_US.utf8
    python setup.py test
    python3 setup.py test
