name       : python-bcrypt
version    : 3.1.7
release    : 6
source     :
    - https://github.com/pyca/bcrypt/archive/3.1.7.tar.gz : 3f7784000846dd85fd626c2cf50065f5078dd76b68f6bd7ba3f132b691035ff4
license    : Apache-2.0
component  : programming.python
summary    : Modern password hashing for your software and your servers
description: |
    Modern password hashing for your software and your servers
builddeps  :
    - pkgconfig(python3)
    - python-cffi
    - python-pytest
rundeps    :
    - python-cffi
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
